export const MESSAGE_CHANNELS = {
  START_INSPECT: 'START_INSPECT',
  STOP_INSPECT: 'STOP_INSPECT',
  INSPECT_SELECTED: 'INSPECT_SELECTED',
  START_SCROLL: 'START_SCROLL',
  STOP_SCROLL: 'STOP_SCROLL',
  NEW_DATA_ITEMS: 'NEW_DATA_ITEMS',
  STATE_CHANGED: 'STATE_CHANGED',
  GET_STATE: 'GET_STATE',
  EXPORT_DATA: 'EXPORT_DATA',
  CLEAR_DATA: 'CLEAR_DATA',
} as const;
